# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76308a1242b4baa425c0f0a19437ddc4cb7968d2940361321d87a1f35cbb5fcb662da504587a2a1f27e145fd59996f49225d54d4500d7eaf64cc161243a3b61f
  stripe_publishable_key: pk_test_4JGjJE8maMlAY8fsNeLb5ROO
  stripe_secret_key: sk_test_nnbypnbV1i8ybFRKVtcF6afh


test:
  secret_key_base: 4f481b63c632464f53193b50b46bab0ff258fb59d296b4b679790d238adb73af7a86169e55d8a5ebbb598864bf96c360dac15a4b4f44fe5e661b5ccde3394da2
  stripe_publishable_key: pk_test_4JGjJE8maMlAY8fsNeLb5ROO
  stripe_secret_key: sk_test_nnbypnbV1i8ybFRKVtcF6afh

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: pk_test_4JGjJE8maMlAY8fsNeLb5ROO
  stripe_secret_key: sk_test_nnbypnbV1i8ybFRKVtcF6afh
